# Generated by Django 5.0.6 on 2024-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_film',
            name='image',
            field=models.ImageField(default='films/img/default.jpeg', upload_to='films/img/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
